### ISSUE TITLE
Crash when accidentally outputting bash color codes

### ISSUE THREAD

**Issue by flokli** [brettstimmerman/jabber-bot#8]
Hi,

I use jabber-bot to (basically) execute some shell commands, and return the output to the user.

The output sometimes contains bash color codes, and when I try to return this output, the jabber-bot goes offline without any error message, but the script still running (and doing nothing).

That error was really hard to find out.

For now I solved it (for my case) by a  

``` ruby
output.gsub(/\x1b\[.{1,5}m/, '').gsub(/\x1b\[K/, '');
```

Before returning the command output.

To help others to not get into the same problem, maybe jabber-bot should "disarm" strings sent back to the server (or at least raise an exception when it fails).

**Comment by brettstimmerman** [comment]
Nice catch!

Given that it's solvable it in an app, I'm not sure it warrants a solution in jabber-bot. Besides, special cases are an extremely slippery slope.

**Comment by flokli** [comment]
I also think that special cases are bad. But something is failing, and we don't get an exception or anything...

Seems to be a problem of xmpp4r-simple, or what do you think?

**Comment by brettstimmerman** [comment]
It's a good question. I wonder if simply escaping the backslashes, or even the entire response with `%q`, are viable alternatives.
